version: "3"
services:

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8081:8081"
    networks:
      - backend-net
          
  backend:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "36150:36150"
    networks: 
     - backend-net
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongo:/data/mongo
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: nico
      MONGODB_INITDB_ROOT_PASSWORD: korczak
    networks: 
     - backend-net

networks:
  backend-net:

volumes: 
  mongo:
