version: "3"
services:


  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - backend
      
      
  api:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    networks: 
     - backend
  
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongo:/data/mongo
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: nico
      MONGODB_INITDB_ROOT_PASSWORD: korczak
    
    networks: 
     - backend

networks:
  backend:

volumes: 
  mongo:
